### ISSUE TITLE
Error: Network request failure: com.google.gson.Gson.newJsonReader...

### ISSUE THREAD

**Issue by ylluminate** [phroa/pm#1]
So after installing the plugin, I attempted a search for a plugin and got an error:

`/ore admin aliases`

> [13:31:28] [pool-2-thread-2/INFO]: Network request failure: com.google.gson.Gson.newJsonReader(Ljava/io/Reader;)Lcom/google/gson/stream/JsonReader;
> [13:31:28] [pool-2-thread-2/INFO]: [STDERR]: java.lang.NoSuchMethodError: com.google.gson.Gson.newJsonReader(Ljava/io/Reader;)Lcom/google/gson/stream/JsonReader;
> [13:31:28] [pool-2-thread-2/INFO]: [STDERR]: 	at net.phroa.pm.shadow.retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:35)
> [13:31:28] [pool-2-thread-2/INFO]: [STDERR]: 	at net.phroa.pm.shadow.retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)
> [13:31:28] [pool-2-thread-2/INFO]: [STDERR]: 	at net.phroa.pm.shadow.retrofit2.ServiceMethod.toResponse(ServiceMethod.java:119)
> [13:31:28] [pool-2-thread-2/INFO]: [STDERR]: 	at net.phroa.pm.shadow.retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:218)
> [13:31:28] [pool-2-thread-2/INFO]: [STDERR]: 	at net.phroa.pm.shadow.retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:112)
> [13:31:28] [pool-2-thread-2/INFO]: [STDERR]: 	at net.phroa.pm.shadow.okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
> [13:31:28] [pool-2-thread-2/INFO]: [STDERR]: 	at net.phroa.pm.shadow.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
> [13:31:28] [pool-2-thread-2/INFO]: [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> [13:31:28] [pool-2-thread-2/INFO]: [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> [13:31:28] [pool-2-thread-2/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:745)
> 

I'm also thinking perhaps the syntax should be modeled after apt/homebrew/yum, etc. vs the current way of invoking?  Eg, `/ore search <plugin_name_or_part_of_name>`, `/ore install <plugin_name>`, `/ore remove <plug_name>`, etc.

**Comment by phroa** [comment]
Thanks for the report, I've just pushed [0.2.1](https://ore.spongepowered.org/phroa/pm/versions/0.2.1-SNAPSHOT) to fix this; apparently SpongeVanilla doesn't shade Gson.

As for the syntax stuff, when I add more features they'll be available through subcommands.
